services:
  arselinux-build:
    container_name: arselinux-build
    image: 'arselinux-build:latest'
    build:
      context: .
      network: host
    restart: "no"
    privileged: true
    network_mode: host
    volumes:
      - ./:/root/ArseLinuxOS-ISO
